#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : libmp3lame
Version  : 3.100
Release  : 4
URL      : file:///insilications/build/clearlinux/packages/libmp3lame/libmp3lame-v3.100.tar.gz
Source0  : file:///insilications/build/clearlinux/packages/libmp3lame/libmp3lame-v3.100.tar.gz
Summary  : High quality MPEG Audio Layer III (MP3) encoder
Group    : Development/Tools
License  : LGPL-3.0-or-later
Requires: libmp3lame-bin = %{version}-%{release}
Requires: libmp3lame-lib = %{version}-%{release}
Requires: libmp3lame-man = %{version}-%{release}
BuildRequires : libsndfile-dev
BuildRequires : libsndfile-staticdev
BuildRequires : nasm-bin
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(sndfile)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
LAME 3.xx
LAME Ain't an MP3 Encoder
http://lame.sf.net
May 2011
Originally developed by Mike Cheng (www.uq.net.au/~zzmcheng) and was
latter developed by Mark Taylor (www.mp3dev.org). Currently maintained
by The LAME Project.

%package bin
Summary: bin components for the libmp3lame package.
Group: Binaries

%description bin
bin components for the libmp3lame package.


%package dev
Summary: dev components for the libmp3lame package.
Group: Development
Requires: libmp3lame-lib = %{version}-%{release}
Requires: libmp3lame-bin = %{version}-%{release}
Provides: libmp3lame-devel = %{version}-%{release}
Requires: libmp3lame = %{version}-%{release}

%description dev
dev components for the libmp3lame package.


%package doc
Summary: doc components for the libmp3lame package.
Group: Documentation
Requires: libmp3lame-man = %{version}-%{release}

%description doc
doc components for the libmp3lame package.


%package lib
Summary: lib components for the libmp3lame package.
Group: Libraries

%description lib
lib components for the libmp3lame package.


%package man
Summary: man components for the libmp3lame package.
Group: Default

%description man
man components for the libmp3lame package.


%package staticdev
Summary: staticdev components for the libmp3lame package.
Group: Default
Requires: libmp3lame-dev = %{version}-%{release}

%description staticdev
staticdev components for the libmp3lame package.


%prep
%setup -q -n libmp3lame
cd %{_builddir}/libmp3lame

%build
## build_prepend content
#find . -type f -name 'configure' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
#find . -type f -name 'configure.*' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
#find . -type f -name 'libtool' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
#find . -type f -name 'libtool.*' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
#find . -type f -name 'Makefile' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
#find . -type f -name 'Makefile.*' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
## build_prepend end
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1600366018
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
export CFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
# -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden -flto-partition=none
# gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common
export CXXFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC"
#
export FCFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
export FFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
export CFFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
#
export LDFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
#
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%define _lto_cflags 1
#%define _lto_cflags %{nil}
#
# export PATH="/usr/lib64/ccache/bin:$PATH"
# export CCACHE_NOHASHDIR=1
# export CCACHE_DIRECT=1
# export CCACHE_SLOPPINESS=pch_defines,locale,time_macros
# export CCACHE_DISABLE=1
## altflags1 end
##
%define _lto_cflags 1
##
%reconfigure --enable-static --enable-shared --enable-nasm --disable-maintainer-mode
## make_prepend content
#find . -type f -name 'configure' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
#find . -type f -name 'libtool' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
#find . -type f -name 'Makefile' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
#find . -type f -name 'config.status' -exec touch {} \;
## make_prepend end
make  %{?_smp_mflags}  V=1 VERBOSE=1


%check
export LANG=C.UTF-8
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1600366018
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lame

%files dev
%defattr(-,root,root,-)
/usr/include/lame/lame.h
/usr/lib64/pkgconfig/lame.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/lame/html/about.html
/usr/share/doc/lame/html/abr.html
/usr/share/doc/lame/html/cbr.html
/usr/share/doc/lame/html/contact.html
/usr/share/doc/lame/html/contributors.html
/usr/share/doc/lame/html/detailed.html
/usr/share/doc/lame/html/history.html
/usr/share/doc/lame/html/index.html
/usr/share/doc/lame/html/introduction.html
/usr/share/doc/lame/html/links.html
/usr/share/doc/lame/html/list.html
/usr/share/doc/lame/html/ms_stereo.html
/usr/share/doc/lame/html/usage.html
/usr/share/doc/lame/html/vbr.html

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmp3lame.so
/usr/lib64/libmp3lame.so.0
/usr/lib64/libmp3lame.so.0.0.0

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/lame.1

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libmp3lame.a
